### ISSUE TITLE
enhance README to explain general capabilities

### ISSUE THREAD

**Issue by pbugni** [uwcirg/hydrant#23]
Others need to be able to glance at the README to determine if this product can or should be extended to handle needs, i.e. how would it generate QuestionnaireResponses from CSV files (what needs to exist in the import format), where it needs to link to existing FHIR resources (Patients, Encounters, Questionnaires).

**Comment by lober** [comment]
Thanks Paul - not sure the Answers->QuestionnaireResonses use case needs to be the focus of a quick enhancement to the README, but I think your goal of "determine if this product can handle, or should be extended to handle" a specific need is a great framing.  Maybe doing that in the context of a use case is good, or maybe that use case is too complicated, at least for an iteration of README you could do in 15 mins or less!

**Comment by lober** [comment]
Assigning you to spend 15 mins adding to README and me to review what you write!
